### PR TITLE
feat: provider-version-branch option

### PR DESCRIPTION
**Pull request by mchwalek**
Resolves issue #327

### CODE REVIEW

**Review by adamrodger — COMMENTED** [review]
Thanks for your submission.

The code itself is fine, but I'm not sure whether it should be merged or not. The problem is that this has changed the public API (by changing a constructor) and is therefore a breaking change which requires a major release.

I don't think we're planning on doing any further major releases before v4.x though, which is a complete rewrite to use the new Rust core instead of Ruby.

**Comment by mchwalek** [comment]
Hi, although I changed the public API, the change itself is backwards compatible (the added argument is optional). Therefore I think it could be a part of a minor release.

BTW the `feature/4.0.0` branch, also lacks the flag added in this PR. Should I make an equivalent PR for that branch?

**Comment by mchwalek** [comment]
@adamrodger Ok, after some research, I'm convinced that my change is not backwards compatible. How about making a constructor overload instead?

**Comment by adamrodger** [comment]
I think this would also need a Ruby core lib upgrade as well now that I think about it. The associated 4.x version needs an FFI upgrade, and presumably this does also. I'm not quite sure how to check what the current Ruby version actually supports though.

**Comment by adamrodger** [comment]
> @adamrodger Ok, after some research, I'm convinced that my change is not backwards compatible. How about making a constructor overload instead?

I think an overload would be the only way you could do it without a breaking change, but I think the API would end up a bit of a mess just because of all the existing optional args. The new param would have to go before all of those optional args, and since it's just a string that would create a pretty error-prone API.

In fact, even that would be a breaking change. Consider this:

```csharp
public class Foo
{
    public Foo (string one, string two = null) { /* ... */ }
}

var foo = new Foo("one", "two");
```

That's fine, you've used the optional param but you didn't need to give it a name. But now someone adds a new constructor with a non-optional param before the optional ones:

```csharp
public class Foo
{
    public Foo (string one, string two = null) { /* ... */ }

    // new ctor with an extra arg before the optional
    public Foo(string one, string added, string two = null) { /* ... */ }
}

// existing code - uh-oh, doesn't this now set `added = "two"` instead of `two = "two"`?
var foo = new Foo("one", "two");
```

So existing code would change meaning, and therefore even that would be a breaking change I think. If I've got that wrong then please let me know.

**Comment by mchwalek** [comment]
@adamrodger So neither a new optional param nor a constructor overload seems to be the proper solution for this. Any suggestions how should this be resolved?

**Comment by adamrodger** [comment]
I'm not really sure. I don't think we want to do a major release as the Ruby core is no longer really recommended, and we're well underway with the replacement.

The existing API is inflexible so I can't see a good way of doing it in a non-breaking way.

**Comment by mchwalek** [comment]
Ok, I'll close this PR then, and focus on the one for 4.0.0 release

**Pull request closed without merging**
