### PR TITLE
Suppress the inclusion of CSS files in the final package.

### LINKED ISSUE #220: NuGet Package Links A Lot of Superfluous Content
The nuge package introduces a lot of superfluous content into the solution, so if, for example, a developer uses Resharper with the default settings, they will see CSS syntax errors from documentation found in the Ruby gems.

image

This has an impact on the "less than native" experience when working with the .Net pact library when compared to the Java implementation.

### PR DESCRIPTION
**Pull request by Silvenga**
Partially resolves #220.

### CODE REVIEW

**Comment by Silvenga** [comment]
Waiting on CI verification.

**Comment by Silvenga** [comment]
I can confirm that the changes suppress the CSS files inclusion in the resulting package:

image

**Comment by bethesque** [comment]
We should be able to exclude those from the source package. I'll have a look.

**Comment by bethesque** [comment]
```
8156173 22 Nov 14:45 pact-1.72.2-osx.tar.gz.before
8142537 22 Nov 14:46 pact-1.72.2-osx.tar.gz.after
```

About 13KB saved, according to my calculations. WIN!!!!

**Pull request merged**
