### PR TITLE
feat: provider-version-branch option

### PR DESCRIPTION
**Pull request by mchwalek**
Resolves issue #327 for 4.0.0 release

### CODE REVIEW

**Comment by mefellows** [comment]
Thank you!

**Comment by adamrodger** [comment]
The FFI version that we're currently on doesn't support this option, so at the moment it'll throw an error I think if you attempt to use it. We need an accompanying FFI upgrade before this can be merged.

**Comment by mchwalek** [comment]
@adamrodger What is the earliest FFI version that supports it? May I create a PR for FFI upgrade?

**Comment by adamrodger** [comment]
I don't know which FFI version supports this, but there's another MR at the moment upgrading to 0.1.5

**Comment by mchwalek** [comment]
@adamrodger 
> there's another MR at the moment upgrading to 0.1.5
I can't find it - was it already merged? If not, could you give me a link?

**Comment by mchwalek** [comment]
@adamrodger Any update regarding FFI upgrade?

**Comment by adamrodger** [comment]
Planning on doing it next week (to fix a big missing feature for verifier
logging by moving to a new API in the FFI)

**Comment by alexthissen** [comment]
Will this do an upgrade to pact_ffi.dll version 0.1.6?

**Comment by adamrodger** [comment]
The 0.1.6 upgrade was already merged in #350

**Comment by alexthissen** [comment]
Thanks for mentioning. I missed that new merge yesterday. :)

**Comment by adamrodger** [comment]
I think this PR may end up being obsolete after #353 because the method for interacting with the core library changes completely. I'll keep you posted

**Comment by alexthissen** [comment]
Will be good to switch to the new model and get output from the provider verification. It will greatly improve writing .NET provider tests when we get feedback on the verification results in the test results.

**Comment by adamrodger** [comment]
Superseded by the move to verifier handles in #353 and then fully supported in #358

**Pull request closed without merging**
