### PR TITLE
feat: update standalone to 1.82.3

### PR DESCRIPTION
**Pull request by bethesque**
For https://github.com/pact-foundation/pact-net/issues/237

### CODE REVIEW

**Comment by neilcampbell** [comment]
Thanks @bethesque. Will get a release out today.

**Comment by bethesque** [comment]
Thanks Neil! I had a look around to see if it was something I could learn to do (despite not having a windows machine 😆) but I couldn't find any release docs. Is it something that could be automated? I have no knowledge of the nuget ecosystem.

**Comment by neilcampbell** [comment]
It is all automated, all you do is create and publish a new GH release (with release notes etc) after merging the changes and it kicks off.

**Comment by neilcampbell** [comment]
Just created the release, which is building now. It'll be available in 2.5.3.

**Pull request merged**
