### PR TITLE
Add support for WIP pacts

### PR DESCRIPTION
**Pull request by tawfiknouri**
Add support for WIP pacts 
https://github.com/pact-foundation/pact-net/issues/247

### CODE REVIEW

**Comment by bethesque** [comment]
Looks good to me 👍

**Comment by bethesque** [comment]
@tawfiknouri could I ask a favour? While you're on a roll, would you be interested in adding `consumer` and `fallbackTag` properties to the consumer version selector object? They were added after Neil did his initial implementation of the new API.

**Comment by tawfiknouri** [comment]
@bethesque, no problem ,Code Done and tests OK, but Nuget pact in CI it's very very slow ....

**Comment by tawfiknouri** [comment]
@bethesque CI is ok now

**Comment by neilcampbell** [comment]
@tawfiknouri Thanks for the PR, all looks good to me.

**Comment by neilcampbell** [comment]
Building now, will be in `2.5.5`

**Comment by tawfiknouri** [comment]
@neilcampbell 
it seems the 2.5.5 not been published
https://www.nuget.org/packages/PactNet/
Can you check CD Pipeline please ?

**Comment by bethesque** [comment]
Snappy turnaround! Thanks guys.

**Comment by neilcampbell** [comment]
@tawfiknouri Sorry about that the build timedout and was offline yesterday. Creating those nuget packages are crazy slow due to all the small ruby files etc. Should be published now!

**Pull request merged**
