### PR TITLE
Change default target framework for .Net Core 

### PR DESCRIPTION
**Pull request by mattermack**
Change default target framework for .Net Core #127

### CODE REVIEW

**Comment by neilcampbell** [comment]
Is there any specific reason to upgrade to the latest? I generally like to keep the version aligned with lowest targeted version of the nuget package, which is netstandard1.5

**Comment by mattermack** [comment]
Below is context on what I'm working on and slightly off topic.   It does help understand the original pull request ...

I'm currently working through a .Net Core v2 app and VS 2017 15.3.  I switched to NUnit over XUnit because of some problems in 15.3 for .Net Core v2 issues.  I still cannot kick off a Consumer test in .Net Core v2 b/c of an inability kick off Ruby.   

So I'm in the process of debugging PactNet, I'm building from source and ramped up the Core versions.   When linking the project, I am coming across this error in 

> System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Cannot mix synchronous and asynchronous operation on process stream.
  Source=System.Diagnostics.Process
  StackTrace:
   at System.Diagnostics.Process.BeginOutputReadLine()
   at PactNet.Core.PactCoreHost`1.Start() in D:\Development\github\pact-net\PactNet\Core\PactCoreHost.cs:line 118
   at PactNet.Mocks.MockHttpService.Host.RubyHttpHost.Start() in D:\Development\github\pact-net\PactNet\Mocks\MockHttpService\Host\RubyHttpHost.cs:line 49
   at PactNet.Mocks.MockHttpService.MockProviderService.Start() in D:\Development\github\pact-net\PactNet\Mocks\MockHttpService\MockProviderService.cs:line 128
   at PactNet.PactBuilder.MockService(Int32 port, JsonSerializerSettings jsonSerializerSettings, Boolean enableSsl, IPAddress host) in D:\Development\github\pact-net\PactNet\PactBuilder.cs:line 86
   at PactNet.PactBuilder.MockService(Int32 port, Boolean enableSsl, IPAddress host) in D:\Development\github\pact-net\PactNet\PactBuilder.cs:line 59
   at PactNetExampleClient.Tests.ExampleApiPact..ctor() in D:\Development\pact-net-example-client\src\PactNetExampleClient.Tests\ExampleApiPact.cs:line 26
   at PactNetExampleClient.Tests.ExampleApiConsumerTests.Setup() in D:\Development\pact-net-example-client\src\PactNetExampleClient.Tests\ExampleApiClientTest.cs:line 20



`public void Start()
 {
            _process.OutputDataReceived += WriteLineToOutput;
            _process.ErrorDataReceived += WriteLineToOutput;

            var success = _process.Start();

            if (!success)
            {
                throw new PactFailureException("Could not start the Pact Core Host");
            }

            _process.BeginOutputReadLine();
`

**Comment by mattermack** [comment]
Ok, I had some odd funky ghost in the machine.  I removed my breakpoints and life is working.  I still like the idea of ramping up the .Net Core version but I'll defer to you as the owner to add or reject the PR.  I appreciate the perspective.

**Comment by mattermack** [comment]
@neilcampbell , if you are interested in the error I was seeing w.r.t. xUnit, it is very similar to https://github.com/xunit/xunit/issues/1483

**Comment by neilcampbell** [comment]
Thanks for the detail and context.
I think for now I will keep it at it's current version.

**Pull request closed without merging**
