### PR TITLE
Message pact latest

### PR DESCRIPTION
**Pull request by arindamdat**
- Merged from master
- All tests have passed

### CODE REVIEW

**Comment by neilcampbell** [comment]
@arindamdat I believe the readme merge may have messed up.
Just wanted to check that the goal of this PR to merge `master` into the `message-pact` branch?

**Comment by arindamdat** [comment]
Hi Neil,
Yes, that's correct.
Thanks and Regards
Arindam Datta
("The only thing necessary for evil to flourish is for good men to do
nothing" - Edmund Burke)

**Comment by drkghost** [comment]
@arindamdat @neilcampbell  Hi, guys,
I'm a bit confused with diff. branches and pr's for the amqp support. 
In addition to the current one, I've found :

    https://github.com/pact-foundation/pact-net/tree/message-pact-2
    https://github.com/pact-foundation/pact-net/tree/message-pact
    active pull-request #175

Which one can be considered as source of truth?
I'd like to help with the implementation of message brokers support, in order to meet pact 3 spec.

Please clarify

**Comment by arindamdat** [comment]
hi @drkghost , as I know, the branch `message-pact` is the one which will be merged into `master `eventually. The goal of this current PR is to merge `master` to the `message-pact` branch.

**Comment by yanncourtel** [comment]
Hi @drkghost, @arindamdat are you actually working on the pact-message branch? I'm also trying to get acclimated with this branch. We implemented the messaging system in our own library in our organisation to free the dev teams but we'd like to also be able to contribute to merge this branch as soon as possible.

**Comment by mefellows** [comment]
Hi @yanncourtel, apologies I missed this. I think we discussed in Slack but Arindam made a small change to just merge latest master in, AFAIK they are not working to add new features to this.

We'd love for this to get merged and will provide any support required. How would you like to proceed?

**Comment by mefellows** [comment]
@HugoDoyon @jacekmlynek what are your thoughts here, any reason not to merge this in and have it supported side-by-side with the current code base?

My fear with long running branches is that it will go stale and never get merged (ala this 2+ year old branch...). It will likely change, but is it better to do that after bringing it in?

**Comment by adamrodger** [comment]
Closed due to #315 being merged instead

**Pull request closed without merging**
